src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $product_name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $product_image = null;

    #[ORM\Column]
    private ?float $product_price = null;

    #[ORM\Column(length: 255)]
    private ?string $product_category = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $product_stock = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $product_description = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $product_advice = null;

    #[ORM\ManyToMany(targetEntity: Commande::class, mappedBy: 'product')]
    private Collection $commandes;

    #[ORM\ManyToOne(inversedBy: 'products')]
    private ?Unit $unit = null;

    public function __construct()
    {
        $this->commandes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductName(): ?string
    {
        return $this->product_name;
    }

    public function setProductName(string $product_name): self
    {
        $this->product_name = $product_name;

        return $this;
    }

    public function getProductImage(): ?string
    {
        return $this->product_image;
    }

    public function setProductImage(string $product_image): self
    {
        $this->product_image = $product_image;

        return $this;
    }

    public function getProductPrice(): ?float
    {
        return $this->product_price;
    }

    public function setProductPrice(float $product_price): self
    {
        $this->product_price = $product_price;

        return $this;
    }

    public function getProductCategory(): ?string
    {
        return $this->product_category;
    }

    public function setProductCategory(string $product_category): self
    {
        $this->product_category = $product_category;

        return $this;
    }

    public function getProductStock(): ?string
    {
        return $this->product_stock;
    }

    public function setProductStock(?string $product_stock): self
    {
        $this->product_stock = $product_stock;

        return $this;
    }

    public function getProductDescription(): ?string
    {
        return $this->product_description;
    }

    public function setProductDescription(?string $product_description): self
    {
        $this->product_description = $product_description;

        return $this;
    }

    public function getProductAdvice(): ?string
    {
        return $this->product_advice;
    }

    public function setProductAdvice(?string $product_advice): self
    {
        $this->product_advice = $product_advice;

        return $this;
    }

    /**
     * @return Collection<int, Commande>
     */
    public function getCommandes(): Collection
    {
        return $this->commandes;
    }

    public function addCommande(Commande $commande): self
    {
        if (!$this->commandes->contains($commande)) {
            $this->commandes->add($commande);
            $commande->addProduct($this);
        }

        return $this;
    }

    public function removeCommande(Commande $commande): self
    {
        if ($this->commandes->removeElement($commande)) {
            $commande->removeProduct($this);
        }

        return $this;
    }

    public function getUnit(): ?Unit
    {
        return $this->unit;
    }

    public function setUnit(?Unit $unit): self
    {
        $this->unit = $unit;

        return $this;
    }

}

templates/card_details_affichage/card_details_affichage.html.twig
    <div class="col-10 col-sm-6 col-md-8 col-lg-7 mb-3">
        <div class="card">
            <div class="row g-0">
                {# image section de gauche#}
                <div class="col-md-6">
                    <img src="{{ asset("build/images/"~item.productImage~"") }}" class="col-12 object-fit-fill h-100" alt="...">
                </div>
                {# prix, titre, tableau section de droite #}
                <div class="d-flex justify-content-center align-items-center align-items-md-start col-md-6">
                    <div class="card-body background-color-grey h-100">
                        {# section titre et prix card produit#}
                        <h3 class="card-title">{{ item.productName }}</h3>
                        <div class="d-flex justify-content-start flex-row my-2 text-black">
                            <p class="card-text">{{ item.productPrice }}€</p>
                        </div>
                        {# fin section titre et prix card produit#}
                        {# section tableau card produit#}
                        <div>
                            <table class="table">
                                <thead class="background-main-color">
                                    <tr>
                                        <th scope="col" class="text-color-card-products">nom</th>

                                        <th scope="col" class="text-color-card-products">PrixTTC</th>
                                    </tr>
                                </thead>
                                <tbody class="background-secondary-color">
                                    <tr>
                                        <td>{{ item.productName |nombre_characteres_nom_produit }}</td>
                                        <td>{{ item.productPrice }}€</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                        {# fin section tableau card produit#}
                    </div>
                </div>
            </div>
        </div>
    </div>